// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolKrFds3dXqNdc1C19FZy-acY0_zZ3hw',
    appId: '1:475939873531:web:4f0d698c4915037acac65e',
    messagingSenderId: '475939873531',
    projectId: 'ocrpoc-13cdf',
    authDomain: 'ocrpoc-13cdf.firebaseapp.com',
    storageBucket: 'ocrpoc-13cdf.appspot.com',
    measurementId: 'G-QLXK8ZE3EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0se06tugr5Q_m9VYCkFfnTYeqack0EQ',
    appId: '1:475939873531:android:9f98d8b636cddf32cac65e',
    messagingSenderId: '475939873531',
    projectId: 'ocrpoc-13cdf',
    storageBucket: 'ocrpoc-13cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqz43-MHFz0wQPscnf_0XcW_QLDzMPHA',
    appId: '1:475939873531:ios:74882761754c7f3ecac65e',
    messagingSenderId: '475939873531',
    projectId: 'ocrpoc-13cdf',
    storageBucket: 'ocrpoc-13cdf.appspot.com',
    iosClientId: '475939873531-dhiqhtfhs9p3daqsukngvci8nofusjsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqz43-MHFz0wQPscnf_0XcW_QLDzMPHA',
    appId: '1:475939873531:ios:9993778894257fd5cac65e',
    messagingSenderId: '475939873531',
    projectId: 'ocrpoc-13cdf',
    storageBucket: 'ocrpoc-13cdf.appspot.com',
    iosClientId: '475939873531-6o3n0d3eln502he3tbd4mb0cskcgil5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrPoc.RunnerTests',
  );
}
